[profile.default]
src = "contracts/src"
test = "contracts/test"
script = "contracts/script"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
evm_version = "cancun"
optimizer = true
optimizer_runs = 700
via_ir = true
verbosity = 2

remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@1inch/solidity-utils/=lib/solidity-utils/",
    "@1inch/aqua/=lib/aqua/",
    "@1inch/swap-vm/=lib/swap-vm/src/",
    "@uniswap/v3-core/=lib/v3-core/",
]

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
